# Generated by Django 3.1.7 on 2021-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fathername',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
